#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0xE02B14E5030A2708 (security@celeryproject.org)
#
Name     : kombu
Version  : 3.0.37
Release  : 31
URL      : http://pypi.debian.net/kombu/kombu-3.0.37.tar.gz
Source0  : http://pypi.debian.net/kombu/kombu-3.0.37.tar.gz
Source99 : http://pypi.debian.net/kombu/kombu-3.0.37.tar.gz.asc
Summary  : Messaging library for Python
Group    : Development/Tools
License  : BSD-3-Clause
Requires: kombu-python3
Requires: kombu-license
Requires: kombu-python
Requires: PyYAML
Requires: amqp
Requires: anyjson
Requires: boto
Requires: kazoo
Requires: librabbitmq
Requires: msgpack-python
Requires: ordereddict
Requires: pymongo
Requires: pyzmq
Requires: qpid-python
Requires: redis
BuildRequires : amqp
BuildRequires : anyjson
BuildRequires : buildreq-distutils3
BuildRequires : linecache2
BuildRequires : nose
BuildRequires : pbr
BuildRequires : pip
BuildRequires : python-mock
BuildRequires : python3-dev
BuildRequires : setuptools
BuildRequires : six
BuildRequires : traceback2
BuildRequires : unittest2

%description
========================================
         kombu - Messaging library for Python
        ========================================

%package license
Summary: license components for the kombu package.
Group: Default

%description license
license components for the kombu package.


%package python
Summary: python components for the kombu package.
Group: Default
Requires: kombu-python3

%description python
python components for the kombu package.


%package python3
Summary: python3 components for the kombu package.
Group: Default
Requires: python3-core

%description python3
python3 components for the kombu package.


%prep
%setup -q -n kombu-3.0.37

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1532210976
python3 setup.py build -b py3

%check
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
PYTHONPATH=%{buildroot}/usr/lib/python3.7/site-packages python3 setup.py test || :
%install
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/doc/kombu
cp LICENSE %{buildroot}/usr/share/doc/kombu/LICENSE
python3 -tt setup.py build -b py3 install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files license
%defattr(-,root,root,-)
/usr/share/doc/kombu/LICENSE

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
